<!doctype html>
<html lang="id" data-bs-theme="light">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Analytics - CRM UMKM</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<style>body{background:#f6f7fb}.metric{border:0;box-shadow:0 4px 18px rgba(0,0,0,.05)}.metric .icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:var(--bs-tertiary-bg)}.chart-card{border:0;box-shadow:0 4px 18px rgba(0,0,0,.05)}.table-card{border:0;box-shadow:0 4px 18px rgba(0,0,0,.05)}.small-muted{font-size:.8rem;color:var(--bs-secondary-color)}</style>
</head>
<body><div class="container-fluid p-3 p-lg-4">
<div class="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-4"><div><h3 class="mb-1">CRM Analytics</h3><div class="text-secondary">Kinerja sales, WhatsApp, AI, dan campaign</div></div><div class="d-flex gap-2"><input id="from" type="date" class="form-control"><input id="to" type="date" class="form-control"><button id="refresh" class="btn btn-dark"><i class="bi bi-arrow-clockwise"></i></button></div></div>
<div id="error" class="alert alert-danger d-none"></div><div id="loading" class="text-secondary py-5 text-center">Memuat analytics...</div>
<div id="content" class="d-none">
<div class="row g-3 mb-4" id="metrics"></div>
<div class="row g-3 mb-4"><div class="col-xl-8"><div class="card chart-card"><div class="card-body"><div class="d-flex justify-content-between"><h6>Pesan Harian</h6><span class="small-muted">Incoming vs outgoing</span></div><canvas id="messageChart" height="110"></canvas></div></div></div><div class="col-xl-4"><div class="card chart-card h-100"><div class="card-body"><h6>Pipeline Terbuka</h6><canvas id="pipelineChart" height="210"></canvas></div></div></div></div>
<div class="row g-3 mb-4"><div class="col-lg-4"><div class="card metric h-100"><div class="card-body"><h6>AI Performance</h6><div class="display-6" id="aiConfidence">0%</div><div class="small-muted">Average confidence</div><hr><div class="d-flex justify-content-between"><span>AI requests</span><b id="aiTotal">0</b></div><div class="d-flex justify-content-between"><span>Human handoff</span><b id="aiHandoff">0%</b></div></div></div></div><div class="col-lg-4"><div class="card metric h-100"><div class="card-body"><h6>Campaign</h6><div class="display-6" id="deliveryRate">0%</div><div class="small-muted">Delivery rate</div><hr><div class="d-flex justify-content-between"><span>Campaign</span><b id="campaigns">0</b></div><div class="d-flex justify-content-between"><span>Read rate</span><b id="readRate">0%</b></div></div></div></div><div class="col-lg-4"><div class="card metric h-100"><div class="card-body"><h6>Sales</h6><div class="display-6" id="wonValue">Rp 0</div><div class="small-muted">Won value in period</div><hr><div class="d-flex justify-content-between"><span>Won deals</span><b id="wonDeals">0</b></div><div class="d-flex justify-content-between"><span>Conversion</span><b id="conversion">0%</b></div></div></div></div></div>
<div class="card table-card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="mb-0">Agent Performance</h6><span class="small-muted">Tenant users</span></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Agent</th><th>Conversations</th><th>Active</th><th>Messages</th></tr></thead><tbody id="agents"></tbody></table></div></div></div>
</div></div>
<script>
const $=id=>document.getElementById(id);let messageChart=null,pipelineChart=null;
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const num=v=>new Intl.NumberFormat('id-ID').format(Number(v||0));
async function api(){const q=new URLSearchParams({from:$('from').value,to:$('to').value});const r=await fetch('/api/analytics/dashboard?'+q,{credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d.message||'Request gagal');return d.data}
function dates(){const now=new Date();const to=now.toISOString().slice(0,10);const from=new Date(now);from.setDate(from.getDate()-29);$('from').value=from.toISOString().slice(0,10);$('to').value=to}
function metric(icon,title,value,sub){return `<div class="col-sm-6 col-xl-3"><div class="card metric h-100"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="small-muted">${title}</div><div class="fs-3 fw-semibold mt-1">${value}</div><div class="small-muted">${sub||''}</div></div><div class="icon"><i class="bi ${icon}"></i></div></div></div></div></div>`}
function render(d){const k=d.kpi||{};$('metrics').innerHTML=metric('bi-people','Total Customers',num(k.customers),`+${num(k.new_customers)} baru`)+metric('bi-chat-dots','Open Conversations',num(k.open_conversations),`${num(k.conversations)} dibuat dalam periode`)+metric('bi-cash-stack','Pipeline Value',money(k.pipeline_value),`${num(k.open_deals)} open deals`)+metric('bi-send','Messages',num(k.messages),`${num(k.incoming_messages)} masuk · ${num(k.outgoing_messages)} keluar`);$('aiConfidence').textContent=(d.ai?.avg_confidence||0)+'%';$('aiTotal').textContent=num(d.ai?.total);$('aiHandoff').textContent=(d.ai?.human_handoff_rate||0)+'%';$('deliveryRate').textContent=(d.campaign?.delivery_rate||0)+'%';$('campaigns').textContent=num(d.campaign?.campaigns);$('readRate').textContent=(d.campaign?.read_rate||0)+'%';$('wonValue').textContent=money(k.won_value);$('wonDeals').textContent=num(k.won_deals);$('conversion').textContent=(k.conversion_rate||0)+'%';
const labels=(d.daily_messages||[]).map(x=>x.day), incoming=(d.daily_messages||[]).map(x=>x.incoming), outgoing=(d.daily_messages||[]).map(x=>x.outgoing);if(messageChart)messageChart.destroy();messageChart=new Chart($('messageChart'),{type:'line',data:{labels,datasets:[{label:'Incoming',data:incoming,tension:.25},{label:'Outgoing',data:outgoing,tension:.25}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}});
if(pipelineChart)pipelineChart.destroy();pipelineChart=new Chart($('pipelineChart'),{type:'doughnut',data:{labels:(d.pipeline||[]).map(x=>x.stage),datasets:[{data:(d.pipeline||[]).map(x=>Number(x.value||0))}]},options:{plugins:{legend:{position:'bottom'}}}});
$('agents').innerHTML=(d.agents||[]).map(a=>`<tr><td><strong>${esc(a.name)}</strong></td><td>${num(a.conversations)}</td><td>${num(a.active_conversations)}</td><td>${num(a.messages)}</td></tr>`).join('')||'<tr><td colspan="4" class="text-secondary">Belum ada data agent.</td></tr>';}
function esc(v){return String(v??'').replace(/[&<>'\"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[x]))}
async function load(){ $('loading').classList.remove('d-none');$('content').classList.add('d-none');$('error').classList.add('d-none');try{render(await api());$('content').classList.remove('d-none')}catch(e){$('error').textContent=e.message;$('error').classList.remove('d-none')}finally{$('loading').classList.add('d-none')}}
$('refresh').onclick=load;dates();load();
</script></body></html>
