<!doctype html>
<html lang="id" data-bs-theme="light">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Inbox — CRM WhatsApp UMKM</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>
:root{--wa:#128c7e;--wa-soft:#e7f7f4}.app{height:100vh;display:grid;grid-template-columns:330px minmax(0,1fr) 310px;background:var(--bs-body-bg)}body{margin:0;overflow:hidden}.pane{min-width:0;height:100vh}.left,.right{overflow:auto;border-color:var(--bs-border-color)}.left{border-right:1px solid}.right{border-left:1px solid}.topbar{height:64px}.searchbox{position:relative}.searchbox i{position:absolute;left:12px;top:9px}.searchbox input{padding-left:34px}.conversation{cursor:pointer;border-bottom:1px solid var(--bs-border-color);transition:.15s}.conversation:hover,.conversation.active{background:var(--bs-secondary-bg)}.avatar{width:42px;height:42px;flex:0 0 42px;border-radius:50%;display:grid;place-items:center;background:var(--wa-soft);color:var(--wa);font-weight:700}.preview{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat{display:flex;flex-direction:column;background:#efeae2}.chat-header{background:var(--bs-body-bg);border-bottom:1px solid var(--bs-border-color)}.messages{flex:1;overflow:auto;padding:24px;background-image:radial-gradient(rgba(0,0,0,.035) 1px,transparent 1px);background-size:18px 18px}.bubble{max-width:min(72%,680px);padding:9px 12px;border-radius:12px;margin:5px 0;box-shadow:0 1px 1px rgba(0,0,0,.08);white-space:pre-wrap;overflow-wrap:anywhere}.incoming{background:var(--bs-body-bg);border-top-left-radius:4px}.outgoing{margin-left:auto;background:#d9fdd3;border-top-right-radius:4px}.meta{font-size:.68rem;opacity:.6;text-align:right;margin-top:3px}.composer{background:var(--bs-body-bg);border-top:1px solid var(--bs-border-color);padding:10px}.composer textarea{resize:none;max-height:120px}.status-dot{width:8px;height:8px;border-radius:50%;display:inline-block;background:#20c997}.section-title{font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;opacity:.6}.tag{font-size:.72rem}.empty{min-height:240px}.mobile-only{display:none}@media(max-width:1100px){.app{grid-template-columns:300px minmax(0,1fr)}.right{display:none}}@media(max-width:720px){.app{display:block}.left{position:absolute;width:100%;z-index:5;background:var(--bs-body-bg);transform:translateX(0);transition:.2s}.left.hidden{transform:translateX(-100%)}.chat{height:100vh}.mobile-only{display:inline-flex}.bubble{max-width:86%}.chat-header{padding-left:8px!important}}
</style>
</head>
<body>
<div class="app">
<aside class="pane left" id="leftPane">
  <div class="topbar d-flex align-items-center justify-content-between px-3 border-bottom">
    <div><div class="fw-bold fs-5">Inbox</div><div class="small text-secondary"><span class="status-dot me-1"></span>Realtime aktif</div></div>
    <button class="btn btn-sm btn-outline-secondary" id="refresh" title="Refresh"><i class="bi bi-arrow-clockwise"></i></button>
  </div>
  <div class="p-3 border-bottom">
    <div class="searchbox"><i class="bi bi-search text-secondary"></i><input id="search" class="form-control" placeholder="Cari nama atau nomor..."></div>
    <div class="d-flex gap-2 mt-2"><select id="status" class="form-select form-select-sm"><option value="">Semua</option><option value="OPEN">Open</option><option value="PENDING">Pending</option><option value="RESOLVED">Resolved</option><option value="ARCHIVED">Archived</option></select><select id="priority" class="form-select form-select-sm"><option value="">Prioritas</option><option>URGENT</option><option>HIGH</option><option>NORMAL</option><option>LOW</option></select></div>
  </div>
  <div id="conversationList"></div>
</aside>
<main class="pane chat">
  <header class="chat-header p-3 d-flex align-items-center justify-content-between">
    <div class="d-flex align-items-center gap-2 min-w-0"><button id="back" class="btn btn-sm btn-outline-secondary mobile-only"><i class="bi bi-arrow-left"></i></button><div class="avatar" id="headerAvatar">?</div><div class="min-w-0"><div id="chatTitle" class="fw-semibold text-truncate">Pilih percakapan</div><div id="chatSubtitle" class="small text-secondary text-truncate">Belum ada percakapan aktif</div></div></div>
    <div id="chatActions" class="d-flex gap-1 d-none"><button id="aiSuggest" class="btn btn-sm btn-outline-primary"><i class="bi bi-stars"></i> AI Suggest</button><button id="handoff" class="btn btn-sm btn-outline-warning"><i class="bi bi-person-raised-hand"></i> Handoff</button><div class="dropdown"><button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown">Status</button><ul class="dropdown-menu dropdown-menu-end"><li><button class="dropdown-item" data-status="OPEN">Open</button></li><li><button class="dropdown-item" data-status="PENDING">Pending</button></li><li><button class="dropdown-item" data-status="RESOLVED">Resolved</button></li><li><button class="dropdown-item" data-status="ARCHIVED">Archived</button></li></ul></div></div>
  </header>
  <div id="messages" class="messages d-flex align-items-center justify-content-center"><div class="text-center text-secondary empty"><i class="bi bi-chat-square-text fs-1 d-block mb-2"></i>Pilih percakapan untuk mulai melayani customer.</div></div>
  <div class="composer">
    <div id="aiDraft" class="alert alert-primary py-2 px-3 small d-none mb-2"><div class="d-flex justify-content-between align-items-start"><div><i class="bi bi-stars me-1"></i><strong>AI Suggestion</strong><div id="aiText" class="mt-1"></div></div><button class="btn-close" id="closeAi"></button></div><button id="useAi" class="btn btn-sm btn-primary mt-2">Gunakan sebagai draft</button></div>
    <div class="input-group align-items-end"><button class="btn btn-outline-secondary" disabled title="Lampiran segera hadir"><i class="bi bi-paperclip"></i></button><textarea id="messageInput" rows="1" class="form-control" placeholder="Ketik balasan..." disabled></textarea><button id="send" class="btn btn-success px-3" disabled><i class="bi bi-send"></i></button></div>
    <div class="small text-secondary mt-1"><span id="sendState">Pilih conversation.</span> · Enter untuk kirim, Shift+Enter untuk baris baru</div>
  </div>
</main>
<aside class="pane right p-3" id="customerPane">
  <div class="section-title mb-3">Customer profile</div>
  <div id="customerInfo" class="text-secondary">Belum ada customer dipilih.</div>
</aside>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.socket.io/4.8.1/socket.io.min.js"></script>
<script>
const state={conversations:[],conversation:null,tenantId:null,realtimeToken:null,socket:null};const $=id=>document.getElementById(id);
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Request gagal');return d}
function esc(v){return String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function initials(name){return String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function time(v){if(!v)return '';const d=new Date(String(v).replace(' ','T'));return isNaN(d)?'':d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function renderConversations(){const s=$('search').value.toLowerCase();const p=$('priority').value;const rows=state.conversations.filter(c=>(!p||c.priority===p)&&(c.customer_name||c.customer_phone||'').toLowerCase().includes(s));$('conversationList').innerHTML=rows.map(c=>`<div class="conversation p-3 ${state.conversation&&Number(state.conversation.id)===Number(c.id)?'active':''}" data-id="${c.id}"><div class="d-flex gap-2"><div class="avatar">${esc(initials(c.customer_name||c.customer_phone))}</div><div class="min-w-0 flex-grow-1"><div class="d-flex justify-content-between gap-2"><strong class="text-truncate">${esc(c.customer_name||c.customer_phone||'Customer')}</strong>${c.unread_count?`<span class="badge text-bg-success rounded-pill">${c.unread_count}</span>`:''}</div><div class="small text-secondary preview">${esc(c.customer_phone||'')}</div><div class="d-flex justify-content-between mt-1"><span class="badge rounded-pill text-bg-light border">${esc(c.status)}</span><span class="small text-secondary">${time(c.last_message_at)}</span></div></div></div></div>`).join('')||'<div class="p-4 text-center text-secondary">Tidak ada conversation.</div>';document.querySelectorAll('.conversation').forEach(x=>x.onclick=()=>openConversation(Number(x.dataset.id)))}
async function loadConversations(){try{const q=new URLSearchParams();if($('status').value)q.set('status',$('status').value);const r=await api('/api/inbox/conversations?'+q);state.conversations=r.data||[];renderConversations()}catch(e){$('conversationList').innerHTML=`<div class="p-3 text-danger">${esc(e.message)}</div>`}}
async function openConversation(id){try{const r=await api('/api/inbox/conversations/'+id+'/messages');state.conversation=r.conversation;renderHeader();renderMessages(r.data||[]);$('messageInput').disabled=false;$('send').disabled=false;$('chatActions').classList.remove('d-none');$('sendState').textContent='Terhubung ke WhatsApp gateway';await api('/api/inbox/conversations/'+id+'/read',{method:'POST'});await loadConversations();$('leftPane').classList.add('hidden')}catch(e){alert(e.message)}}
function renderHeader(){const c=state.conversation;const name=c.customer_name||c.customer_phone||'Customer';$('headerAvatar').textContent=initials(name);$('chatTitle').textContent=name;$('chatSubtitle').textContent=`${c.customer_phone||'-'} · ${c.status} · ${c.priority||'NORMAL'}${Number(c.ai_enabled)?' · AI aktif':''}`;$('handoff').classList.toggle('btn-warning',Number(c.ai_enabled)===1);$('handoff').classList.toggle('btn-outline-warning',Number(c.ai_enabled)!==1);$('customerInfo').innerHTML=`<div class="d-flex align-items-center gap-2 mb-3"><div class="avatar">${esc(initials(name))}</div><div><div class="fw-semibold">${esc(name)}</div><div class="small text-secondary">${esc(c.customer_phone||'-')}</div></div></div><div class="border-top pt-3"><div class="section-title mb-2">Conversation</div><div class="d-flex justify-content-between mb-2"><span>Status</span><strong>${esc(c.status)}</strong></div><div class="d-flex justify-content-between mb-2"><span>Priority</span><strong>${esc(c.priority||'NORMAL')}</strong></div><div class="d-flex justify-content-between mb-2"><span>AI</span><strong>${Number(c.ai_enabled)?'Aktif':'Human'}</strong></div><div class="d-flex justify-content-between"><span>Assigned</span><strong>${esc(c.assigned_name||'Belum ditugaskan')}</strong></div></div><div class="border-top mt-3 pt-3"><div class="section-title mb-2">Quick actions</div><button class="btn btn-sm btn-outline-secondary w-100 mb-2" id="analyzeBtn"><i class="bi bi-graph-up"></i> Analisis percakapan</button><div id="analysis" class="small text-secondary"></div></div>`;$('analyzeBtn').onclick=analyzeConversation}
function renderMessages(rows){$('messages').className='messages';$('messages').innerHTML=rows.length?rows.map(m=>`<div class="bubble ${m.direction==='INCOMING'?'incoming':'outgoing'}"><div>${esc(m.body||('['+m.message_type+']'))}</div><div class="meta">${time(m.timestamp)} ${m.direction==='OUTGOING'?' · '+esc(m.status||'SENT'):''}</div></div>`).join(''):'<div class="text-center text-secondary m-auto">Belum ada pesan.</div>';$('messages').scrollTop=$('messages').scrollHeight}
async function sendMessage(){if(!state.conversation)return;const input=$('messageInput'),text=input.value.trim();if(!text)return;input.disabled=true;$('send').disabled=true;try{await api('/api/inbox/conversations/'+state.conversation.id+'/send',{method:'POST',body:JSON.stringify({text})});input.value='';await openConversation(state.conversation.id)}catch(e){alert(e.message)}finally{input.disabled=false;$('send').disabled=false;input.focus()}}
async function aiSuggest(){if(!state.conversation)return;const b=$('aiSuggest');b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span> Generating...';try{const r=await api('/api/ai/conversations/'+state.conversation.id+'/suggest',{method:'POST',body:JSON.stringify({style:'friendly'})});const d=r.data||{};const text=d.reply||d.suggestion||d.text||'';if(!text)throw new Error('AI tidak menghasilkan suggestion.');$('aiText').textContent=text;$('aiDraft').classList.remove('d-none')}catch(e){alert(e.message)}finally{b.disabled=false;b.innerHTML='<i class="bi bi-stars"></i> AI Suggest'}}
async function analyzeConversation(){if(!state.conversation)return;const el=$('analysis');el.textContent='Menganalisis...';try{const r=await api('/api/ai/conversations/'+state.conversation.id+'/analyze',{method:'POST'});const d=r.data||{};el.innerHTML=`<div class="mb-1"><b>Intent:</b> ${esc(d.intent||'-')}</div><div class="mb-1"><b>Sentiment:</b> ${esc(d.sentiment||'-')}</div><div><b>Lead score:</b> ${esc(d.lead_score??'-')}</div>`}catch(e){el.textContent=e.message}}
async function handoff(){if(!state.conversation)return;const next=!Number(state.conversation.ai_enabled);try{await api('/api/ai/conversations/'+state.conversation.id+'/handoff',{method:'PATCH',body:JSON.stringify({ai_enabled:next})});state.conversation.ai_enabled=next?1:0;renderHeader()}catch(e){alert(e.message)}}
async function changeStatus(status){if(!state.conversation)return;try{const r=await api('/api/inbox/conversations/'+state.conversation.id,{method:'PATCH',body:JSON.stringify({status})});state.conversation=r.data;renderHeader();await loadConversations()}catch(e){alert(e.message)}}
async function connectRealtime(){try{const r=await api('/api/inbox/realtime-token');state.realtimeToken=r.data.token;state.tenantId=r.data.tenant_id;state.socket=io({auth:{token:state.realtimeToken},transports:['websocket','polling']});state.socket.on('connect',()=>{$('sendState').textContent=state.conversation?'Terhubung · realtime':'Realtime aktif'});state.socket.on('connect_error',()=>{$('sendState').textContent='Realtime gagal terhubung; refresh untuk mencoba lagi'});state.socket.on('whatsapp.message',d=>{if(state.conversation&&((d.conversation_id&&Number(d.conversation_id)===Number(state.conversation.id))||(d.remote_jid&&d.remote_jid===state.conversation.remote_jid))){openConversation(state.conversation.id)}else loadConversations()});state.socket.on('realtime.ready',()=>loadConversations())}catch(e){console.warn('Realtime unavailable',e.message)}}
$('refresh').onclick=loadConversations;$('status').onchange=loadConversations;$('priority').onchange=renderConversations;$('search').oninput=renderConversations;$('send').onclick=sendMessage;$('aiSuggest').onclick=aiSuggest;$('handoff').onclick=handoff;$('back').onclick=()=>$('leftPane').classList.remove('hidden');$('closeAi').onclick=()=>$('aiDraft').classList.add('d-none');$('useAi').onclick=()=>{if($('aiText').textContent){$('messageInput').value=$('aiText').textContent;$('messageInput').focus();$('aiDraft').classList.add('d-none')}};document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>changeStatus(b.dataset.status));$('messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('messageInput').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,120)+'px'});
Promise.all([loadConversations(),connectRealtime()]);
</script>
</body></html>
