<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class InitialSchema extends Migration
{
    public function up()
    {
        $db = $this->db;
        $tables = [
            "CREATE TABLE tenants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL, slug VARCHAR(160) NOT NULL UNIQUE, status ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE', timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Jakarta', created_at DATETIME NULL, updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(255) NULL, created_at DATETIME NULL, updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, created_at DATETIME NULL, updated_at DATETIME NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id, permission_id), CONSTRAINT fk_rp_role FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, CONSTRAINT fk_rp_permission FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, role_id BIGINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL, password_hash VARCHAR(255) NOT NULL, status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE', last_login_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_user_tenant_email(tenant_id,email), KEY idx_user_tenant(tenant_id), CONSTRAINT fk_user_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_user_role FOREIGN KEY(role_id) REFERENCES roles(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE whatsapp_devices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, phone_number VARCHAR(30) NULL, session_id VARCHAR(120) NOT NULL UNIQUE, status ENUM('CONNECTED','CONNECTING','DISCONNECTED','QR_REQUIRED','RECONNECTING','LOGGED_OUT','ERROR') NOT NULL DEFAULT 'DISCONNECTED', connection_state VARCHAR(30) NULL, last_connected_at DATETIME NULL, last_disconnected_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_device_tenant(tenant_id), CONSTRAINT fk_device_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE customers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, phone VARCHAR(30) NOT NULL, name VARCHAR(150) NULL, email VARCHAR(190) NULL, company VARCHAR(150) NULL, address TEXT NULL, source VARCHAR(80) NULL, status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', owner_id BIGINT UNSIGNED NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_customer_phone(tenant_id,phone), KEY idx_customer_owner(owner_id), CONSTRAINT fk_customer_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_customer_owner FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE conversations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NULL, customer_id BIGINT UNSIGNED NOT NULL, status ENUM('OPEN','PENDING','RESOLVED','ARCHIVED') NOT NULL DEFAULT 'OPEN', assigned_to BIGINT UNSIGNED NULL, last_message_at DATETIME NULL, unread_count INT UNSIGNED NOT NULL DEFAULT 0, ai_enabled TINYINT(1) NOT NULL DEFAULT 1, priority ENUM('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL', created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_conv_tenant(tenant_id), KEY idx_conv_customer(customer_id), CONSTRAINT fk_conv_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_conv_device FOREIGN KEY(device_id) REFERENCES whatsapp_devices(id) ON DELETE SET NULL, CONSTRAINT fk_conv_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE, CONSTRAINT fk_conv_assignee FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, conversation_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NULL, message_id VARCHAR(190) NOT NULL, remote_jid VARCHAR(190) NOT NULL, sender_type ENUM('CUSTOMER','AGENT','SYSTEM') NOT NULL, sender_phone VARCHAR(30) NULL, message_type VARCHAR(40) NOT NULL DEFAULT 'text', body LONGTEXT NULL, media_url VARCHAR(500) NULL, media_mime VARCHAR(120) NULL, quoted_message_id VARCHAR(190) NULL, status ENUM('PENDING','SENT','DELIVERED','READ','FAILED') NOT NULL DEFAULT 'PENDING', direction ENUM('INCOMING','OUTGOING') NOT NULL, timestamp DATETIME NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_message(tenant_id,device_id,message_id), KEY idx_msg_conversation(conversation_id), KEY idx_msg_timestamp(timestamp), CONSTRAINT fk_msg_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_msg_conv FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE, CONSTRAINT fk_msg_device FOREIGN KEY(device_id) REFERENCES whatsapp_devices(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(80) NULL, entity_id BIGINT UNSIGNED NULL, ip_address VARCHAR(45) NULL, user_agent VARCHAR(500) NULL, metadata JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_audit_tenant(tenant_id), CONSTRAINT fk_audit_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_audit_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        ];
        foreach ($tables as $sql) { $db->query($sql); }
    }

    public function down()
    {
        foreach (['audit_logs','messages','conversations','customers','whatsapp_devices','users','role_permissions','permissions','roles','tenants'] as $table) {
            $this->db->query('DROP TABLE IF EXISTS ' . $this->db->protectIdentifiers($table));
        }
    }
}
