<?php
namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class EngagementSchema extends Migration
{
    public function up()
    {
        $sql = [
            "CREATE TABLE message_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, category VARCHAR(80) NULL, body TEXT NOT NULL, variables_json JSON NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_template_tenant_name(tenant_id,name), KEY idx_template_tenant(tenant_id), CONSTRAINT fk_template_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE campaigns (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(180) NOT NULL, template_id BIGINT UNSIGNED NULL, message_body TEXT NULL, segment_json JSON NULL, scheduled_at DATETIME NULL, timezone VARCHAR(80) NULL, status VARCHAR(30) NOT NULL DEFAULT 'DRAFT', rate_limit_per_minute INT UNSIGNED NOT NULL DEFAULT 20, total_recipients INT UNSIGNED NOT NULL DEFAULT 0, sent_count INT UNSIGNED NOT NULL DEFAULT 0, delivered_count INT UNSIGNED NOT NULL DEFAULT 0, read_count INT UNSIGNED NOT NULL DEFAULT 0, failed_count INT UNSIGNED NOT NULL DEFAULT 0, created_by BIGINT UNSIGNED NULL, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_campaign_tenant_status(tenant_id,status), KEY idx_campaign_scheduled(scheduled_at), CONSTRAINT fk_campaign_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_campaign_template FOREIGN KEY(template_id) REFERENCES message_templates(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE campaign_recipients (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, campaign_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, phone VARCHAR(30) NOT NULL, rendered_body TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', message_id VARCHAR(150) NULL, error_message TEXT NULL, sent_at DATETIME NULL, delivered_at DATETIME NULL, read_at DATETIME NULL, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_campaign_customer(campaign_id,customer_id), KEY idx_cr_tenant_status(tenant_id,status), KEY idx_cr_campaign(campaign_id), CONSTRAINT fk_cr_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_cr_campaign FOREIGN KEY(campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE, CONSTRAINT fk_cr_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE scheduled_messages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, device_id BIGINT UNSIGNED NULL, template_id BIGINT UNSIGNED NULL, body TEXT NOT NULL, scheduled_at DATETIME NOT NULL, timezone VARCHAR(80) NULL, status VARCHAR(30) NOT NULL DEFAULT 'PENDING', attempts TINYINT UNSIGNED NOT NULL DEFAULT 0, max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 3, last_error TEXT NULL, message_id VARCHAR(150) NULL, sent_at DATETIME NULL, created_by BIGINT UNSIGNED NULL, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_sm_due(status,scheduled_at), KEY idx_sm_tenant(tenant_id), CONSTRAINT fk_sm_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_sm_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE, CONSTRAINT fk_sm_template FOREIGN KEY(template_id) REFERENCES message_templates(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE automation_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(180) NOT NULL, trigger_event VARCHAR(80) NOT NULL, conditions_json JSON NULL, actions_json JSON NOT NULL, enabled TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_ar_tenant_enabled(tenant_id,enabled), KEY idx_ar_trigger(trigger_event), CONSTRAINT fk_ar_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE automation_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, automation_rule_id BIGINT UNSIGNED NOT NULL, event_id VARCHAR(150) NULL, status VARCHAR(30) NOT NULL, input_json JSON NULL, output_json JSON NULL, error_message TEXT NULL, started_at DATETIME NULL, finished_at DATETIME NULL, created_at DATETIME NULL, KEY idx_al_tenant_created(tenant_id,created_at), KEY idx_al_rule(rule_id), CONSTRAINT fk_al_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_al_rule FOREIGN KEY(automation_rule_id) REFERENCES automation_rules(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE opt_outs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, channel VARCHAR(30) NOT NULL DEFAULT 'WHATSAPP', reason VARCHAR(255) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_optout(tenant_id,customer_id,channel), CONSTRAINT fk_optout_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_optout_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        ];
        foreach ($sql as $query) $this->db->query($query);
    }

    public function down()
    {
        foreach (['opt_outs','automation_logs','automation_rules','scheduled_messages','campaign_recipients','campaigns','message_templates'] as $table) $this->db->query('DROP TABLE IF EXISTS ' . $this->db->protectIdentifiers($table));
    }
}
