<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CrmSalesSchema extends Migration
{
    public function up()
    {
        $sql = [
            "CREATE TABLE tags (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(80) NOT NULL, color VARCHAR(20) NULL, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_tag_tenant_name(tenant_id,name), KEY idx_tag_tenant(tenant_id), CONSTRAINT fk_tag_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE customer_tags (customer_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, created_at DATETIME NULL, PRIMARY KEY(customer_id,tag_id), CONSTRAINT fk_ct_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE, CONSTRAINT fk_ct_tag FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE customer_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL, body TEXT NOT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_cn_customer(customer_id), CONSTRAINT fk_cn_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_cn_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE, CONSTRAINT fk_cn_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE pipelines (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, is_default TINYINT(1) NOT NULL DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL, UNIQUE KEY uq_pipeline_tenant_name(tenant_id,name), CONSTRAINT fk_pipeline_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE pipeline_stages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, pipeline_id BIGINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, position INT UNSIGNED NOT NULL DEFAULT 0, probability DECIMAL(5,2) NOT NULL DEFAULT 0, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_stage_pipeline(pipeline_id), CONSTRAINT fk_stage_pipeline FOREIGN KEY(pipeline_id) REFERENCES pipelines(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE deals (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, pipeline_id BIGINT UNSIGNED NOT NULL, stage_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NULL, owner_id BIGINT UNSIGNED NULL, title VARCHAR(180) NOT NULL, value DECIMAL(18,2) NOT NULL DEFAULT 0, currency CHAR(3) NOT NULL DEFAULT 'IDR', status ENUM('OPEN','WON','LOST') NOT NULL DEFAULT 'OPEN', expected_close_date DATE NULL, notes TEXT NULL, created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_deal_tenant(tenant_id), KEY idx_deal_stage(stage_id), CONSTRAINT fk_deal_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_deal_pipeline FOREIGN KEY(pipeline_id) REFERENCES pipelines(id) ON DELETE CASCADE, CONSTRAINT fk_deal_stage FOREIGN KEY(stage_id) REFERENCES pipeline_stages(id) ON DELETE RESTRICT, CONSTRAINT fk_deal_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL, CONSTRAINT fk_deal_owner FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE tasks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NULL, deal_id BIGINT UNSIGNED NULL, assigned_to BIGINT UNSIGNED NULL, title VARCHAR(180) NOT NULL, description TEXT NULL, due_at DATETIME NULL, status ENUM('OPEN','IN_PROGRESS','DONE','CANCELLED') NOT NULL DEFAULT 'OPEN', priority ENUM('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL', created_at DATETIME NULL, updated_at DATETIME NULL, KEY idx_task_tenant(tenant_id), KEY idx_task_due(due_at), CONSTRAINT fk_task_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_task_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL, CONSTRAINT fk_task_deal FOREIGN KEY(deal_id) REFERENCES deals(id) ON DELETE SET NULL, CONSTRAINT fk_task_user FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE activities (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED NULL, conversation_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NULL, type VARCHAR(50) NOT NULL, title VARCHAR(180) NOT NULL, body TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_activity_customer(customer_id), KEY idx_activity_conv(conversation_id), CONSTRAINT fk_activity_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_activity_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL, CONSTRAINT fk_activity_conv FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE SET NULL, CONSTRAINT fk_activity_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE message_attachments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, message_id BIGINT UNSIGNED NOT NULL, storage_path VARCHAR(500) NOT NULL, original_name VARCHAR(255) NULL, mime_type VARCHAR(120) NULL, size_bytes BIGINT UNSIGNED NULL, created_at DATETIME NULL, KEY idx_attachment_message(message_id), CONSTRAINT fk_attachment_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE, CONSTRAINT fk_attachment_message FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        ];
        foreach ($sql as $query) $this->db->query($query);
    }

    public function down()
    {
        foreach (['message_attachments','activities','tasks','deals','pipeline_stages','pipelines','customer_notes','customer_tags','tags'] as $table) {
            $this->db->query('DROP TABLE IF EXISTS ' . $this->db->protectIdentifiers($table));
        }
    }
}
