<!doctype html>
<html lang="id" data-bs-theme="light">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Customer 360 - CRM UMKM</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>
html,body{background:var(--bs-tertiary-bg)}.hero{background:linear-gradient(135deg,var(--bs-dark),#343a40);color:#fff;border-radius:18px}.avatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#fff;color:#212529;font-weight:700;font-size:1.25rem}.stat{border:1px solid var(--bs-border-color);border-radius:14px;padding:14px;background:var(--bs-body-bg)}.card-soft{border:1px solid var(--bs-border-color);border-radius:16px;background:var(--bs-body-bg)}.timeline{position:relative;padding-left:24px}.timeline:before{content:"";position:absolute;left:8px;top:5px;bottom:5px;width:2px;background:var(--bs-border-color)}.event{position:relative;margin-bottom:18px}.event:before{content:"";position:absolute;left:-20px;top:4px;width:10px;height:10px;border-radius:50%;background:var(--bs-primary)}.badge-tag{border:1px solid var(--bs-border-color);padding:.35rem .55rem;border-radius:999px;font-size:.78rem}.deal-card,.task-card{border:1px solid var(--bs-border-color);border-radius:12px;padding:12px}.small-muted{font-size:.8rem;color:var(--bs-secondary-color)}.click{cursor:pointer}.scroll-pane{max-height:430px;overflow:auto}
</style>
</head>
<body>
<div class="container-fluid py-3 py-lg-4" style="max-width:1500px">
<div id="alert"></div>
<div id="hero" class="hero p-3 p-lg-4 mb-3"></div>
<div class="row g-3 mb-3" id="stats"></div>
<div class="row g-3">
<div class="col-xl-8">
<div class="card-soft p-3 mb-3"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Activity Timeline</h5><button class="btn btn-sm btn-outline-primary" onclick="openNote()"><i class="bi bi-journal-plus"></i> Catatan</button></div><div id="timeline" class="timeline scroll-pane"></div></div>
<div class="card-soft p-3 mb-3"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Deals & Sales</h5><button class="btn btn-sm btn-primary" onclick="openDeal()"><i class="bi bi-plus-lg"></i> Deal</button></div><div id="deals" class="vstack gap-2"></div></div>
<div class="card-soft p-3"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Tasks</h5><button class="btn btn-sm btn-outline-primary" onclick="openTask()"><i class="bi bi-check2-square"></i> Task</button></div><div id="tasks" class="vstack gap-2"></div></div>
</div>
<div class="col-xl-4">
<div class="card-soft p-3 mb-3"><div class="d-flex justify-content-between align-items-center"><h6 class="mb-0">Customer Profile</h6><a id="chatBtn" class="btn btn-sm btn-success"><i class="bi bi-whatsapp"></i> Inbox</a></div><div id="profile" class="mt-3"></div></div>
<div class="card-soft p-3 mb-3"><h6>Tags</h6><div id="tags" class="d-flex flex-wrap gap-2"></div><div class="input-group input-group-sm mt-3"><select id="tagSelect" class="form-select"></select><button class="btn btn-outline-primary" onclick="addTag()">Tambah</button></div></div>
<div class="card-soft p-3 mb-3"><h6>WhatsApp Conversations</h6><div id="conversations" class="vstack gap-2 scroll-pane"></div></div>
<div class="card-soft p-3"><div class="d-flex justify-content-between align-items-center"><h6 class="mb-0">AI Lead Insight</h6><button class="btn btn-sm btn-outline-dark" onclick="analyze()"><i class="bi bi-stars"></i></button></div><div id="insight" class="small-muted mt-3">Klik tombol AI untuk menganalisis conversation terbaru.</div></div>
</div>
</div>
</div>
<div class="modal fade" id="modal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 id="modalTitle" class="modal-title"></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div id="modalBody" class="modal-body"></div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Batal</button><button id="modalSave" class="btn btn-primary">Simpan</button></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
const customerId=<?= (int)$customerId ?>;let state={data:null,pipelines:[],tags:[]};let modal=new bootstrap.Modal('#modal');const $=id=>document.getElementById(id);
async function api(url,opts={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Request gagal');return d}
function esc(v){return String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function money(v,c='IDR'){return new Intl.NumberFormat('id-ID',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(v||0))}
function initials(n){return String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function flash(msg,type='success'){ $('alert').innerHTML=`<div class="alert alert-${type} alert-dismissible fade show">${esc(msg)}<button class="btn-close" data-bs-dismiss="alert"></button></div>` }
async function load(){try{const [w,p,t]=await Promise.all([api(`/api/customers/${customerId}/workspace`),api('/api/pipelines'),api('/api/tags')]);state.data=w.data;state.pipelines=p.data||[];state.tags=t.data||[];render()}catch(e){$('alert').innerHTML=`<div class="alert alert-danger">${esc(e.message)}</div>`}}
function render(){const d=state.data,c=d.customer;$('hero').innerHTML=`<div class="d-flex flex-wrap gap-3 align-items-center justify-content-between"><div class="d-flex gap-3 align-items-center"><div class="avatar">${esc(initials(c.name||c.phone))}</div><div><div class="text-white-50 small">CUSTOMER 360</div><h3 class="mb-1">${esc(c.name||'Tanpa nama')}</h3><div class="text-white-50">${esc(c.phone)} ${c.company?` · ${esc(c.company)}`:''}</div></div></div><div class="d-flex gap-2"><button class="btn btn-light" onclick="editCustomer()"><i class="bi bi-pencil"></i> Edit</button><a id="heroChat" class="btn btn-success"><i class="bi bi-chat-dots"></i> Buka Inbox</a></div></div>`;$('profile').innerHTML=`<div class="row g-2 small"><div class="col-12"><b>Telepon</b><div>${esc(c.phone)}</div></div><div class="col-12"><b>Email</b><div>${esc(c.email||'-')}</div></div><div class="col-12"><b>Perusahaan</b><div>${esc(c.company||'-')}</div></div><div class="col-12"><b>Sumber</b><div>${esc(c.source||'-')}</div></div><div class="col-12"><b>Status</b><div><span class="badge text-bg-success">${esc(c.status)}</span></div></div><div class="col-12"><b>Alamat</b><div>${esc(c.address||'-')}</div></div></div>`;bindInbox();$('chatBtn').href='/inbox';
const s=d.stats;$('stats').innerHTML=[['Percakapan',s.conversations,'bi-chat-square-text'],['Pesan',s.messages,'bi-chat-left-text'],['Open Deals',s.open_deals,'bi-kanban'],['Pipeline Value',money(s.open_deals_value),'bi-cash-stack']].map(x=>`<div class="col-6 col-md-3"><div class="stat"><div class="small-muted"><i class="bi ${x[2]}"></i> ${x[0]}</div><div class="fs-4 fw-semibold mt-1">${esc(x[1])}</div></div></div>`).join('');
$('tags').innerHTML=(d.tags||[]).map(t=>`<span class="badge-tag">${esc(t.name)} <button class="btn btn-sm p-0 ms-1" onclick="removeTag(${t.id})">×</button></span>`).join('')||'<span class="small-muted">Belum ada tag.</span>';$('tagSelect').innerHTML='<option value="">Pilih tag...</option>'+state.tags.filter(t=>!(d.tags||[]).some(x=>x.id==t.id)).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');
$('conversations').innerHTML=(d.conversations||[]).map(c=>`<div class="border rounded p-2 click" onclick="location.href='/inbox?conversation=${c.id}'"><div class="d-flex justify-content-between"><b>${esc(c.status)}</b><span class="badge text-bg-${c.unread_count?'success':'secondary'}">${c.unread_count||0} unread</span></div><div class="small-muted">${esc(c.device_name||'WhatsApp')} · ${esc(c.assigned_name||'Unassigned')}</div><div class="small">${c.last_message_at?esc(c.last_message_at):'Belum ada pesan'}</div></div>`).join('')||'<span class="small-muted">Belum ada conversation.</span>';
$('deals').innerHTML=(d.deals||[]).map(x=>`<div class="deal-card"><div class="d-flex justify-content-between gap-2"><div><b>${esc(x.title)}</b><div class="small-muted">${esc(x.pipeline_name)} · ${esc(x.stage_name)} · ${esc(x.owner_name||'Unassigned')}</div></div><div class="text-end"><b>${money(x.value,x.currency)}</b><div><span class="badge text-bg-${x.status==='WON'?'success':x.status==='LOST'?'danger':'primary'}">${x.status}</span></div></div></div><div class="d-flex gap-2 mt-2"><select class="form-select form-select-sm" onchange="changeStage(${x.id},this.value)"><option value="">Ubah stage...</option>${(state.pipelines.find(p=>p.id==x.pipeline_id)?.stages||[]).map(st=>`<option value="${st.id}" ${st.id==x.stage_id?'selected':''}>${esc(st.name)}</option>`).join('')}</select><select class="form-select form-select-sm" onchange="changeDealStatus(${x.id},this.value)">${['OPEN','WON','LOST'].map(st=>`<option ${x.status===st?'selected':''}>${st}</option>`).join('')}</select></div></div>`).join('')||'<span class="small-muted">Belum ada deal.</span>';
$('tasks').innerHTML=(d.tasks||[]).map(x=>`<div class="task-card"><div class="d-flex justify-content-between gap-2"><div><b>${esc(x.title)}</b><div class="small-muted">${x.due_at?esc(x.due_at):'Tanpa deadline'} ${x.deal_title?` · ${esc(x.deal_title)}`:''}</div></div><select class="form-select form-select-sm" style="max-width:150px" onchange="changeTask(${x.id},this.value)">${['OPEN','IN_PROGRESS','DONE','CANCELLED'].map(st=>`<option ${x.status===st?'selected':''}>${st}</option>`).join('')}</select></div></div>`).join('')||'<span class="small-muted">Belum ada task.</span>';
$('timeline').innerHTML=(d.activities||[]).map(a=>`<div class="event"><div class="fw-semibold">${esc(a.title)}</div><div class="small-muted">${esc(a.type)} · ${esc(a.user_name||'System')} · ${esc(a.created_at)}</div><div class="mt-1 small">${esc(a.body||'')}</div></div>`).join('')||'<div class="small-muted">Belum ada aktivitas.</div>';
$('insight').textContent='Klik tombol AI untuk menganalisis conversation terbaru.';}
function bindInbox(){const cs=state.data.conversations||[];const first=cs[0];$('heroChat').href=first?`/inbox?conversation=${first.id}`:'/inbox'}
function openNote(){ $('modalTitle').textContent='Tambah Catatan';$('modalBody').innerHTML='<textarea id="noteBody" class="form-control" rows="5" placeholder="Catatan customer..."></textarea>';$('modalSave').onclick=async()=>{const body=$('noteBody').value.trim();if(!body)return;await api(`/api/customers/${customerId}/notes`,{method:'POST',body:JSON.stringify({body})});modal.hide();await load();flash('Catatan ditambahkan.')};modal.show() }
function openTask(){ $('modalTitle').textContent='Buat Task';$('modalBody').innerHTML='<input id="taskTitle" class="form-control mb-2" placeholder="Follow up customer..."/><input id="taskDue" type="datetime-local" class="form-control mb-2"/><select id="taskPriority" class="form-select"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>URGENT</option></select>';$('modalSave').onclick=async()=>{const title=$('taskTitle').value.trim();if(!title)return;await api(`/api/customers/${customerId}/tasks`,{method:'POST',body:JSON.stringify({title,due_at:$('taskDue').value?$('taskDue').value.replace('T',' '):null,priority:$('taskPriority').value})});modal.hide();await load();flash('Task dibuat.')};modal.show() }
function openDeal(){const opts=state.pipelines.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('modalTitle').textContent='Buat Deal';$('modalBody').innerHTML=`<input id="dealTitle" class="form-control mb-2" placeholder="Nama deal"/><div class="row g-2"><div class="col-6"><select id="dealPipeline" class="form-select">${opts}</select></div><div class="col-6"><select id="dealStage" class="form-select"></select></div><div class="col-6"><input id="dealValue" type="number" class="form-control" placeholder="Nilai"/></div><div class="col-6"><input id="dealDate" type="date" class="form-control"/></div></div>`;const pipe=$('dealPipeline');function stages(){const p=state.pipelines.find(x=>x.id==pipe.value);$('dealStage').innerHTML=(p?.stages||[]).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}pipe.onchange=stages;stages();$('modalSave').onclick=async()=>{const title=$('dealTitle').value.trim();if(!title)return;await api(`/api/customers/${customerId}/deals`,{method:'POST',body:JSON.stringify({title,pipeline_id:Number(pipe.value),stage_id:Number($('dealStage').value),value:Number($('dealValue').value||0),expected_close_date:$('dealDate').value||null})});modal.hide();await load();flash('Deal dibuat.')};modal.show()}
async function addTag(){const id=Number($('tagSelect').value);if(!id)return;await api(`/api/customers/${customerId}/tags/${id}`,{method:'POST'});await load();flash('Tag ditambahkan.')}
async function removeTag(id){await api(`/api/customers/${customerId}/tags/${id}`,{method:'DELETE'});await load();flash('Tag dihapus.')}
async function changeStage(id,stageId){if(!stageId)return;await api(`/api/customers/${customerId}/deals/${id}`,{method:'PATCH',body:JSON.stringify({stage_id:Number(stageId)})});await load()}
async function changeDealStatus(id,status){await api(`/api/customers/${customerId}/deals/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}
async function changeTask(id,status){await api(`/api/customers/${customerId}/tasks/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}
function editCustomer(){const c=state.data.customer;$('modalTitle').textContent='Edit Customer';$('modalBody').innerHTML=`<input id="cName" class="form-control mb-2" value="${esc(c.name)}" placeholder="Nama"/><input id="cEmail" class="form-control mb-2" value="${esc(c.email||'')}" placeholder="Email"/><input id="cCompany" class="form-control mb-2" value="${esc(c.company||'')}" placeholder="Perusahaan"/><textarea id="cAddress" class="form-control">${esc(c.address||'')}</textarea>`;$('modalSave').onclick=async()=>{await api(`/api/customers/${customerId}`,{method:'PUT',body:JSON.stringify({name:$('cName').value,email:$('cEmail').value,company:$('cCompany').value,address:$('cAddress').value})});modal.hide();await load();flash('Profil diperbarui.')};modal.show()}
async function analyze(){const cs=state.data.conversations||[];if(!cs.length){flash('Belum ada conversation untuk dianalisis.','warning');return}try{const r=await api(`/api/ai/conversations/${cs[0].id}/analyze`,{method:'POST'});const d=r.data||{};$('insight').innerHTML=`<div><b>Intent:</b> ${esc(d.intent||'-')}</div><div><b>Sentiment:</b> ${esc(d.sentiment||'-')}</div><div><b>Lead Score:</b> ${esc(d.lead_score??'-')}</div><div class="mt-2">${esc(d.summary||'')}</div>`}catch(e){$('insight').textContent=e.message}}
load();
</script>
</body></html>
